export const product = [
  {
    name: "Graphic T-Shirt",
    image: "/assets/swaatika/7.jpg",
    newArrival: true,
    latest: true,
    actualPrice: 25,
    offerPrice: 20,
    description: "Fun graphic t-shirt for everyday wear.",
    stock: 100,
  },
  {
    name: "Denim Overalls",
    image: "/assets/swaatika/3.jpg",
    newArrival: false,
    latest: true,
    actualPrice: 45,
    offerPrice: 40,
    description: "Comfortable denim overalls for active kids.",
    stock: 35,
  },
  {
    name: "Puffer Jacket",
    image: "/assets/swaatika/16.jpg",
    newArrival: false,
    latest: false,
    actualPrice: 65,
    offerPrice: 60,
    description: "Lightweight puffer jacket for chilly days.",
    stock: 50,
  },
  {
    name: "Cotton Hoodie",
    image: "/assets/swaatika/13.jpg",
    newArrival: true,
    latest: false,
    actualPrice: 30,
    offerPrice: 25,
    description: "Soft cotton hoodie in vibrant colors.",
    stock: 85,
  },
  {
    name: "Running Shoes",
    image: "/assets/swaatika/12.jpg",
    newArrival: true,
    latest: true,
    actualPrice: 120,
    offerPrice: 100,
    description: "Lightweight running shoes with superior grip.",
    stock: 60,
  },
  {
    name: "Leather Boots",
    image: "/assets/swaatika/4.jpg",
    newArrival: false,
    latest: true,
    actualPrice: 180,
    offerPrice: 160,
    description: "Durable leather boots for outdoor adventures.",
    stock: 30,
  },
  {
    name: "Casual Sneakers",
    image: "/assets/swaatika/15.jpg",
    newArrival: false,
    latest: false,
    actualPrice: 90,
    offerPrice: 80,
    description: "Comfortable sneakers for daily wear.",
    stock: 75,
  },
  {
    name: "Sandals",
    image: "/assets/swaatika/9.jpg",
    newArrival: true,
    latest: false,
    actualPrice: 45,
    offerPrice: 40,
    description: "Breathable sandals perfect for summer outings.",
    stock: 90,
  },
];
